---
- name: Apache web server dengan ansibel & docker
  hosts: localhost
  vars_files:
    - vars.yml
  become: true
  tasks:
      - name: Stop a container
        docker_container:
          name: webserver_apache
          state: absent
